/* GENERATED by `node tools/storyboards.mjs` — do not edit by hand.
   Film scrub frames: 48 frames per film made from the film itself (360px tall), in photos/scrub/<id>/.
   sheets: cols x rows frames of w x h each, left→right, top→bottom; `count` frames over `duration` s. */
window.STORYBOARDS = {
  "gItPFC-qhic": {"sheets":["photos/scrub/gItPFC-qhic/M1.webp","photos/scrub/gItPFC-qhic/M2.webp","photos/scrub/gItPFC-qhic/M3.webp","photos/scrub/gItPFC-qhic/M4.webp"],"cols":4,"rows":3,"w":640,"h":360,"count":48,"interval":2.7692,"duration":133},
  "HeRs2D2EXSk": {"sheets":["photos/scrub/HeRs2D2EXSk/M1.webp","photos/scrub/HeRs2D2EXSk/M2.webp","photos/scrub/HeRs2D2EXSk/M3.webp","photos/scrub/HeRs2D2EXSk/M4.webp"],"cols":4,"rows":3,"w":480,"h":360,"count":48,"interval":0.4401,"duration":21},
  "p14Mww6wgkk": {"sheets":["photos/scrub/p14Mww6wgkk/M1.webp","photos/scrub/p14Mww6wgkk/M2.webp","photos/scrub/p14Mww6wgkk/M3.webp","photos/scrub/p14Mww6wgkk/M4.webp"],"cols":4,"rows":3,"w":640,"h":360,"count":48,"interval":3.9835,"duration":191},
  "-pC_MCcH4c8": {"sheets":["photos/scrub/-pC_MCcH4c8/M1.webp","photos/scrub/-pC_MCcH4c8/M2.webp","photos/scrub/-pC_MCcH4c8/M3.webp","photos/scrub/-pC_MCcH4c8/M4.webp"],"cols":4,"rows":3,"w":640,"h":360,"count":48,"interval":2.7933,"duration":134},
  "t32fPgJ2FIs": {"sheets":["photos/scrub/t32fPgJ2FIs/M1.webp","photos/scrub/t32fPgJ2FIs/M2.webp","photos/scrub/t32fPgJ2FIs/M3.webp","photos/scrub/t32fPgJ2FIs/M4.webp"],"cols":4,"rows":3,"w":640,"h":360,"count":48,"interval":1.055,"duration":51},
  "qu7cYF-YV8M": {"sheets":["photos/scrub/qu7cYF-YV8M/M1.webp","photos/scrub/qu7cYF-YV8M/M2.webp","photos/scrub/qu7cYF-YV8M/M3.webp","photos/scrub/qu7cYF-YV8M/M4.webp"],"cols":4,"rows":3,"w":640,"h":360,"count":48,"interval":5.705,"duration":274},
  "RKI861xIfTA": {"sheets":["photos/scrub/RKI861xIfTA/M1.webp","photos/scrub/RKI861xIfTA/M2.webp","photos/scrub/RKI861xIfTA/M3.webp","photos/scrub/RKI861xIfTA/M4.webp"],"cols":4,"rows":3,"w":640,"h":360,"count":48,"interval":0.7665,"duration":37},
  "D7eYTmT5DbY": {"sheets":["photos/scrub/D7eYTmT5DbY/M1.webp","photos/scrub/D7eYTmT5DbY/M2.webp","photos/scrub/D7eYTmT5DbY/M3.webp","photos/scrub/D7eYTmT5DbY/M4.webp"],"cols":4,"rows":3,"w":640,"h":360,"count":48,"interval":1.3594,"duration":65}
};
