/* GENERATED by `node tools/storyboards.mjs` — do not edit by hand.
   Film scrub frames: YouTube storyboard sprite sheets, copied into photos/storyboards/<id>/.
   sheets: cols x rows frames of w x h each, left→right, top→bottom; `count` frames over `duration` s. */
window.STORYBOARDS = {
  "gItPFC-qhic": {"sheets":["photos/storyboards/gItPFC-qhic/M0.webp","photos/storyboards/gItPFC-qhic/M1.webp","photos/storyboards/gItPFC-qhic/M2.webp"],"cols":5,"rows":5,"w":160,"h":90,"count":68,"interval":1.9559,"duration":133},
  "HeRs2D2EXSk": {"sheets":["photos/storyboards/HeRs2D2EXSk/M0.webp"],"cols":5,"rows":5,"w":120,"h":90,"count":23,"interval":0.913,"duration":21},
  "p14Mww6wgkk": {"sheets":["photos/storyboards/p14Mww6wgkk/M0.webp","photos/storyboards/p14Mww6wgkk/M1.webp","photos/storyboards/p14Mww6wgkk/M2.webp","photos/storyboards/p14Mww6wgkk/M3.webp"],"cols":5,"rows":5,"w":160,"h":90,"count":97,"interval":1.9691,"duration":191},
  "-pC_MCcH4c8": {"sheets":["photos/storyboards/-pC_MCcH4c8/M0.webp","photos/storyboards/-pC_MCcH4c8/M1.webp","photos/storyboards/-pC_MCcH4c8/M2.webp"],"cols":5,"rows":5,"w":160,"h":90,"count":69,"interval":1.942,"duration":134},
  "t32fPgJ2FIs": {"sheets":["photos/storyboards/t32fPgJ2FIs/M0.webp","photos/storyboards/t32fPgJ2FIs/M1.webp","photos/storyboards/t32fPgJ2FIs/M2.webp"],"cols":5,"rows":5,"w":160,"h":90,"count":52,"interval":0.9808,"duration":51},
  "qu7cYF-YV8M": {"sheets":["photos/storyboards/qu7cYF-YV8M/M0.webp","photos/storyboards/qu7cYF-YV8M/M1.webp","photos/storyboards/qu7cYF-YV8M/M2.webp","photos/storyboards/qu7cYF-YV8M/M3.webp","photos/storyboards/qu7cYF-YV8M/M4.webp","photos/storyboards/qu7cYF-YV8M/M5.webp"],"cols":5,"rows":5,"w":160,"h":90,"count":138,"interval":1.9855,"duration":274},
  "RKI861xIfTA": {"sheets":["photos/storyboards/RKI861xIfTA/M0.webp","photos/storyboards/RKI861xIfTA/M1.webp"],"cols":5,"rows":5,"w":160,"h":90,"count":38,"interval":0.9737,"duration":37},
  "D7eYTmT5DbY": {"sheets":["photos/storyboards/D7eYTmT5DbY/M0.webp","photos/storyboards/D7eYTmT5DbY/M1.webp","photos/storyboards/D7eYTmT5DbY/M2.webp"],"cols":5,"rows":5,"w":160,"h":90,"count":67,"interval":0.9701,"duration":65},
};
